/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Objects.Categorias;
import Objects.Productos;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static interfaces.VtnLogin.con;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author david
 */
public class VtnGestionProductosGerente extends javax.swing.JFrame
{

    static DefaultTableModel modelo;
    static Boolean edicion = false;
    static Categorias[] cat;

    /**
     * Creates new form VtnMainAdmin
     */
    public VtnGestionProductosGerente()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Acciones = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLTipoSucursal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLEstado = new javax.swing.JLabel();
        txtnnomProducto = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        jLTipoSucursal1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtPrecio_ventas = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPrecio_fabricacion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLEstado1 = new javax.swing.JLabel();
        jcategoria = new javax.swing.JComboBox<>();
        btnnuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLNameUser1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        productos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLWelcome = new javax.swing.JLabel();
        jLIconAdmin = new javax.swing.JLabel();
        jLNameUser = new javax.swing.JLabel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EliminarActionPerformed(evt);
            }
        });
        Acciones.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificarActionPerformed(evt);
            }
        });
        Acciones.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal Administrador");
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(223, 227, 238));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator3.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 10));

        jLTipoSucursal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLTipoSucursal.setForeground(new java.awt.Color(59, 89, 152));
        jLTipoSucursal.setText("Nombre producto:");
        jPanel2.add(jLTipoSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator4.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 10));

        jLEstado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(59, 89, 152));
        jLEstado.setText("Descripcion:");
        jPanel2.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtnnomProducto.setBackground(new java.awt.Color(223, 227, 238));
        txtnnomProducto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtnnomProducto.setForeground(new java.awt.Color(59, 89, 152));
        txtnnomProducto.setBorder(null);
        txtnnomProducto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtnnomProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtnnomProductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtnnomProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 150, 20));

        jLDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(59, 89, 152));
        jLDireccion.setText("Precio fabricacion");
        jPanel2.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator5.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, 10));

        txtDescripcion.setBackground(new java.awt.Color(223, 227, 238));
        txtDescripcion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(59, 89, 152));
        txtDescripcion.setBorder(null);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtDescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtDescripcionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 20));

        jLTipoSucursal1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLTipoSucursal1.setForeground(new java.awt.Color(59, 89, 152));
        jLTipoSucursal1.setText("Precio venta");
        jPanel2.add(jLTipoSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator6.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 150, 10));

        txtPrecio_ventas.setBackground(new java.awt.Color(223, 227, 238));
        txtPrecio_ventas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPrecio_ventas.setForeground(new java.awt.Color(59, 89, 152));
        txtPrecio_ventas.setBorder(null);
        txtPrecio_ventas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtPrecio_ventasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtPrecio_ventasKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 150, 20));

        btncancelar.setBackground(new java.awt.Color(59, 89, 152));
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 100, 40));

        jButton1.setBackground(new java.awt.Color(59, 89, 152));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 100, 40));

        txtPrecio_fabricacion.setBackground(new java.awt.Color(223, 227, 238));
        txtPrecio_fabricacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtPrecio_fabricacion.setForeground(new java.awt.Color(59, 89, 152));
        txtPrecio_fabricacion.setBorder(null);
        txtPrecio_fabricacion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtPrecio_fabricacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtPrecio_fabricacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio_fabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 150, 20));

        jSeparator7.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator7.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, 10));

        jLEstado1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLEstado1.setForeground(new java.awt.Color(59, 89, 152));
        jLEstado1.setText("Categoria:");
        jPanel2.add(jLEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jcategoria.setBackground(new java.awt.Color(223, 227, 238));
        jcategoria.setForeground(new java.awt.Color(59, 89, 152));
        jcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, -1));

        btnnuevo.setBackground(new java.awt.Color(59, 89, 152));
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, 40));

        jButton2.setBackground(new java.awt.Color(59, 89, 152));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Administrar Categorias");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, 40));

        jPanel3.setBackground(new java.awt.Color(223, 227, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNameUser1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLNameUser1.setForeground(new java.awt.Color(59, 89, 152));
        jLNameUser1.setText("Gestión Productos");
        jPanel3.add(jLNameUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 110));

        jSeparator8.setBackground(new java.awt.Color(139, 157, 195));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 150, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 810));

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setForeground(new java.awt.Color(247, 247, 247));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(Acciones);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTable1.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 350));

        btneliminar.setBackground(new java.awt.Color(59, 89, 152));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 150, 40));

        btnmodificar.setBackground(new java.awt.Color(59, 89, 152));
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 150, 40));

        productos.setBackground(new java.awt.Color(59, 89, 152));
        productos.setForeground(new java.awt.Color(255, 255, 255));
        productos.setText("Lista de productos");
        productos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                productosActionPerformed(evt);
            }
        });
        jPanel4.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 150, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 1000, 700));

        jPanel5.setBackground(new java.awt.Color(139, 157, 195));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLWelcome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLWelcome.setForeground(new java.awt.Color(223, 227, 238));
        jLWelcome.setText("Bienvenido:");
        jPanel5.add(jLWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLIconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gerente.png"))); // NOI18N
        jPanel5.add(jLIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLNameUser.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLNameUser.setForeground(new java.awt.Color(223, 227, 238));
        jPanel5.add(jLNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar2.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMousePressed(evt);
            }
        });
        jPanel5.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 30, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar2.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLCerrarMousePressed(evt);
            }
        });
        jPanel5.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 30, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 1000, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMousePressed
    {//GEN-HEADEREND:event_jLCerrarMousePressed
        this.dispose();
        new VtnMainAdmin().setVisible(true);
    }//GEN-LAST:event_jLCerrarMousePressed

    private void jLMinimizarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMousePressed
    {//GEN-HEADEREND:event_jLMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMousePressed

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseEntered
    {//GEN-HEADEREND:event_jLCerrarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/cerrar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseExited
    {//GEN-HEADEREND:event_jLCerrarMouseExited
        ImageIcon icon = new ImageIcon("src/images/cerrar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLMinimizarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseEntered
    {//GEN-HEADEREND:event_jLMinimizarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/minimizar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseEntered

    private void jLMinimizarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseExited
    {//GEN-HEADEREND:event_jLMinimizarMouseExited
        ImageIcon icon = new ImageIcon("src/images/minimizar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CrearModelo();
        llenaCategoria();
        llenaTabla();
        cjb.ci.CtrlInterfaz.habilita(edicion, jcategoria, txtDescripcion, txtnnomProducto, txtPrecio_ventas);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btncancelar);
        jLNameUser.setText(VtnLogin.emp.getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cjb.ci.CtrlInterfaz.limpia(txtDescripcion, txtnnomProducto, txtPrecio_fabricacion, txtPrecio_ventas);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        edicion = false;
        cjb.ci.CtrlInterfaz.habilita(edicion, jcategoria, txtDescripcion, txtnnomProducto, txtPrecio_ventas);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btnmodificar, btncancelar);
        cjb.ci.CtrlInterfaz.limpia(txtDescripcion, txtnnomProducto, txtPrecio_ventas);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (!edicion)
        {
            txtnnomProducto.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1)));
            jcategoria.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)));
            txtDescripcion.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3)));
            txtPrecio_fabricacion.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4)));
            txtPrecio_ventas.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5)));
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void txtnnomProductoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnnomProductoKeyPressed
    {//GEN-HEADEREND:event_txtnnomProductoKeyPressed
        Validaciones.enter(this, evt, txtDescripcion);
    }//GEN-LAST:event_txtnnomProductoKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescripcionKeyPressed
    {//GEN-HEADEREND:event_txtDescripcionKeyPressed
        Validaciones.enter(this, evt, txtPrecio_fabricacion);
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtnnomProductoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnnomProductoKeyTyped
    {//GEN-HEADEREND:event_txtnnomProductoKeyTyped

    }//GEN-LAST:event_txtnnomProductoKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtDescripcionKeyTyped
    {//GEN-HEADEREND:event_txtDescripcionKeyTyped

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtPrecio_ventasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPrecio_ventasKeyTyped
    {//GEN-HEADEREND:event_txtPrecio_ventasKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_txtPrecio_ventasKeyTyped

    private void txtPrecio_ventasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPrecio_ventasKeyPressed
    {//GEN-HEADEREND:event_txtPrecio_ventasKeyPressed
        Validaciones.enter(this, evt, btnnuevo);
    }//GEN-LAST:event_txtPrecio_ventasKeyPressed

    private void txtPrecio_fabricacionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPrecio_fabricacionKeyPressed
    {//GEN-HEADEREND:event_txtPrecio_fabricacionKeyPressed
        Validaciones.enter(this, evt, txtPrecio_ventas);
    }//GEN-LAST:event_txtPrecio_fabricacionKeyPressed

    private void txtPrecio_fabricacionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPrecio_fabricacionKeyTyped
    {//GEN-HEADEREND:event_txtPrecio_fabricacionKeyTyped
        Validaciones.validaFlotantes(evt);
    }//GEN-LAST:event_txtPrecio_fabricacionKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EliminarActionPerformed
    {//GEN-HEADEREND:event_EliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificarActionPerformed
    {//GEN-HEADEREND:event_ModificarActionPerformed
        modifica();
    }//GEN-LAST:event_ModificarActionPerformed

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        JasperReport reporte; //Creo el objeto reporte
        // Ubicacion del Reporte
        String path = "src\\Reportes\\productos.jasper";
        try
        {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Cargo el reporte al objeto
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint, false); //Creamos la vista del Reporte
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex)
        {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productosActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        modifica();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new VtnGestionCategorias().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void llenaTabla()
    {
//        Sucursal suc = new Sucursal();
//        modelo.addRow(suc.consultaMultipleMat(VtnLogin.con));
        modelo.setRowCount(0);
        try
        {
            PreparedStatement ps;
            ResultSet rs;
            String sql = "SELECT id_productos,nombre_producto ,nombre_categoria,productos.descripcion,precio_fabricacion,precio_venta FROM productos "
                    + "inner join categorias on categorias.id_categoria = productos.id_categoria";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rrsw = rs.getMetaData();
            int cantcolumnas = rrsw.getColumnCount();
            Object[] filas = new Object[cantcolumnas];
            while (rs.next())
            {
                for (int i = 0; i < cantcolumnas; i++)
                {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (Exception e)
        {
            System.out.println("Error" + e.toString());
        }
    }

    private void CrearModelo()
    {
        try
        {
            modelo = (new DefaultTableModel(
                    null, new String[]
                    {
                        "ID producto", "Nombre", "Categoria", "Descripcion", "Precio Fabricacion", "Precio Venta"
                    })
            {
                Class[] types = new Class[]
                {
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                };
                boolean[] canEdit = new boolean[]
                {
                    false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex)
                {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex)
                {
                    return canEdit[colIndex];
                }
            });
            jTable1.setModel(modelo);
//            jTable1.getColumn("id_sucursal").setPreferredWidth(0);
//            jTable1.getColumn("id_sucursal").setMinWidth(0);
//            jTable1.getColumn("id_sucursal").setWidth(0);
//            jTable1.getColumn("id_sucursal").setMaxWidth(0);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    public void llenaCategoria()
    {

        Categorias categorias = new Categorias();
        cat = categorias.consultaMultipleVec(con);
        if (cat != null)
        {
            jcategoria.removeAllItems();;
            for (int i = 0; i < cat.length; i++)
            {
                jcategoria.addItem(cat[i].getNombre_categoria());
            }
        } else
        {
            Mensaje.error(this, "no carga estados");
        }
    }

    public int ExtraeId(String nombre)
    {
        for (int i = 0; i < cat.length; i++)
        {
            if (cat[i].getNombre_categoria().equals(nombre))
            {
                System.out.println("id_categorias" + cat[i].getId_categoria());
                return cat[i].getId_categoria();
            }
        }
        System.out.println("Retornando 0");
        return 0;
    }

    public void nuevo()
    {
        if (edicion)
        {
            if (Mensaje.pregunta(this, "¿Seguro que quiere dar de alta?") == JOptionPane.YES_OPTION)
            {
                Productos pro = new Productos(0,
                        txtnnomProducto.getText(),
                        ExtraeId(String.valueOf(jcategoria.getSelectedItem())),
                        txtDescripcion.getText(),
                        Float.parseFloat(txtPrecio_fabricacion.getText()),
                        Float.parseFloat(txtPrecio_ventas.getText()));
                pro.inserta(this, pro, con);
                llenaTabla();
                edicion = false;
                cjb.ci.CtrlInterfaz.habilita(edicion, txtDescripcion, txtnnomProducto, txtPrecio_ventas, jcategoria, txtPrecio_fabricacion);
                cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btnmodificar, btncancelar);
                btnnuevo.setText("Nuevo");
            }

        } else
        {
            edicion = true;
            CtrlInterfaz.selecciona(txtnnomProducto);
            cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btnmodificar);
            cjb.ci.CtrlInterfaz.habilita(edicion, jcategoria, txtDescripcion, txtnnomProducto, txtPrecio_ventas);
            cjb.ci.CtrlInterfaz.limpia(txtDescripcion, txtnnomProducto, txtPrecio_fabricacion, txtPrecio_ventas);
            btnnuevo.setText("Aceptar");
        }
    }

    public void eliminar()
    {
        try
        {
            if (Mensaje.pregunta(this, "¿Seguro que quiere eliminar a " + jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1) + "?") == JOptionPane.YES_OPTION)
            {
                Productos pro = new Productos();
                pro.elimina(this, Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))), con);
                llenaTabla();

            }

        } catch (Exception e)
        {
            Mensaje.error(this, "Selecione un elemento de la tabla");
            System.out.println(e.toString());
        }
    }

    public void modifica()
    {
        try
        {
            if (edicion)
            {
                if (Mensaje.pregunta(this, "¿Seguro que quiere dar de editar a " + jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1) + "?") == JOptionPane.YES_OPTION)
                {
                    Productos pro = new Productos(
                            Integer.parseInt(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0))),
                            txtnnomProducto.getText(),
                            ExtraeId(String.valueOf(jcategoria.getSelectedItem())),
                            txtDescripcion.getText(),
                            Float.parseFloat(txtPrecio_fabricacion.getText()),
                            Float.parseFloat(txtPrecio_ventas.getText()));
                    pro.modifica(this, pro, con);
                    llenaTabla();
                    edicion = false;
                    CtrlInterfaz.selecciona(txtnnomProducto);
                    cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btnmodificar);
                    cjb.ci.CtrlInterfaz.habilita(edicion, jcategoria, txtDescripcion, txtnnomProducto, txtPrecio_ventas);
                    cjb.ci.CtrlInterfaz.limpia(txtDescripcion, txtnnomProducto, txtPrecio_fabricacion, txtPrecio_ventas);
                }

            } else
            {
                if (null == jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))
                {

                }
                edicion = true;
                cjb.ci.CtrlInterfaz.habilita(edicion, txtDescripcion, txtnnomProducto, txtPrecio_ventas, jcategoria, txtPrecio_fabricacion);
                cjb.ci.CtrlInterfaz.habilita(!edicion, btneliminar, btncancelar);

            }
        } catch (Exception e)
        {
            Mensaje.error(this, "Selecione un elemento de la tabla");
            System.out.println(e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("GTK".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionProductosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionProductosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionProductosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionProductosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnGestionProductosGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Acciones;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLEstado1;
    private javax.swing.JLabel jLIconAdmin;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLNameUser1;
    private javax.swing.JLabel jLTipoSucursal;
    private javax.swing.JLabel jLTipoSucursal1;
    private javax.swing.JLabel jLWelcome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcategoria;
    private javax.swing.JButton productos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio_fabricacion;
    private javax.swing.JTextField txtPrecio_ventas;
    private javax.swing.JTextField txtnnomProducto;
    // End of variables declaration//GEN-END:variables

}
