/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Objects.Empleados;
import Objects.Sucursal;
import Objects.Tipo_usuario;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import static interfaces.VtnGestionSucursal.modelo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static interfaces.VtnLogin.con;
import java.security.Principal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author david
 */
public class VtnGestionEmpleadosGerente extends javax.swing.JFrame
{

    static boolean edicion = false;
    static Tipo_usuario[] tipo;
    static Sucursal[] suc;
    Date fcha;

    /**
     * Creates new form VtnMainAdmin
     */
    public VtnGestionEmpleadosGerente()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Acciones = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLNombreEmpleado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtapellidoPaterno = new javax.swing.JTextField();
        jLAPaterno = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLSexo = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtcurp = new javax.swing.JTextField();
        jLCurp = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txttelefono = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLTelefono = new javax.swing.JLabel();
        jLIDSucursal = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLCorreo = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtcorreo = new javax.swing.JTextField();
        jLContra = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtcontraseña = new javax.swing.JTextField();
        jLAMaterno = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtapellidoMaterno = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLIDTipoUsuario = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnlimpia = new javax.swing.JButton();
        jcsucursal = new javax.swing.JComboBox<>();
        jctipoUsuario = new javax.swing.JComboBox<>();
        jcsexo = new javax.swing.JComboBox<>();
        txtfecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLNameUser1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btnelimiar = new javax.swing.JButton();
        btnempleados = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLWelcome = new javax.swing.JLabel();
        jLIconAdmin = new javax.swing.JLabel();
        jLNameUser = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jLMinimizar = new javax.swing.JLabel();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EliminarActionPerformed(evt);
            }
        });
        Acciones.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificarActionPerformed(evt);
            }
        });
        Acciones.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal Administrador");
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(223, 227, 238));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setBackground(new java.awt.Color(223, 227, 238));
        txtnombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(59, 89, 152));
        txtnombre.setBorder(null);
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtnombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, 20));

        jLNombreEmpleado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLNombreEmpleado.setForeground(new java.awt.Color(59, 89, 152));
        jLNombreEmpleado.setText("Nombre del empleado:");
        jPanel2.add(jLNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator2.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 150, 10));

        jSeparator3.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator3.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 150, 10));

        txtapellidoPaterno.setBackground(new java.awt.Color(223, 227, 238));
        txtapellidoPaterno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtapellidoPaterno.setForeground(new java.awt.Color(59, 89, 152));
        txtapellidoPaterno.setBorder(null);
        txtapellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtapellidoPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtapellidoPaternoKeyTyped(evt);
            }
        });
        jPanel2.add(txtapellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 20));

        jLAPaterno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLAPaterno.setForeground(new java.awt.Color(59, 89, 152));
        jLAPaterno.setText("Apellido paterno:");
        jPanel2.add(jLAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator4.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 10));

        jLSexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLSexo.setForeground(new java.awt.Color(59, 89, 152));
        jLSexo.setText("Sexo:");
        jPanel2.add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLFechaNac.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLFechaNac.setForeground(new java.awt.Color(59, 89, 152));
        jLFechaNac.setText("Fecha de nacimiento:");
        jPanel2.add(jLFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator5.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 150, 10));

        txtcurp.setBackground(new java.awt.Color(223, 227, 238));
        txtcurp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtcurp.setForeground(new java.awt.Color(59, 89, 152));
        txtcurp.setBorder(null);
        txtcurp.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtcurpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtcurpKeyTyped(evt);
            }
        });
        jPanel2.add(txtcurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 150, 20));

        jLCurp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLCurp.setForeground(new java.awt.Color(59, 89, 152));
        jLCurp.setText("CURP:");
        jPanel2.add(jLCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator6.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 150, 10));

        txttelefono.setBackground(new java.awt.Color(223, 227, 238));
        txttelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(59, 89, 152));
        txttelefono.setBorder(null);
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txttelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txttelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 150, 20));

        jSeparator7.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator7.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 150, 10));

        jLTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(59, 89, 152));
        jLTelefono.setText("Telefono de contacto:");
        jPanel2.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLIDSucursal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLIDSucursal.setForeground(new java.awt.Color(59, 89, 152));
        jLIDSucursal.setText("Sucursal:");
        jPanel2.add(jLIDSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator8.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 10));

        jLCorreo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(59, 89, 152));
        jLCorreo.setText("Correo:");
        jPanel2.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator9.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 150, 10));

        txtcorreo.setBackground(new java.awt.Color(223, 227, 238));
        txtcorreo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(59, 89, 152));
        txtcorreo.setBorder(null);
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtcorreoKeyPressed(evt);
            }
        });
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 150, 20));

        jLContra.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLContra.setForeground(new java.awt.Color(59, 89, 152));
        jLContra.setText("Contraseña:");
        jPanel2.add(jLContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator10.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 150, 10));

        txtcontraseña.setBackground(new java.awt.Color(223, 227, 238));
        txtcontraseña.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtcontraseña.setForeground(new java.awt.Color(59, 89, 152));
        txtcontraseña.setBorder(null);
        txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtcontraseñaKeyPressed(evt);
            }
        });
        jPanel2.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 20));

        jLAMaterno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLAMaterno.setForeground(new java.awt.Color(59, 89, 152));
        jLAMaterno.setText("Apellido materno:");
        jPanel2.add(jLAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator11.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 150, 10));

        txtapellidoMaterno.setBackground(new java.awt.Color(223, 227, 238));
        txtapellidoMaterno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtapellidoMaterno.setForeground(new java.awt.Color(59, 89, 152));
        txtapellidoMaterno.setBorder(null);
        txtapellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtapellidoMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtapellidoMaternoKeyTyped(evt);
            }
        });
        jPanel2.add(txtapellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 150, 20));

        jSeparator12.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator12.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 10));

        jLIDTipoUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLIDTipoUsuario.setForeground(new java.awt.Color(59, 89, 152));
        jLIDTipoUsuario.setText("Tipo usuario:");
        jPanel2.add(jLIDTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnnuevo.setBackground(new java.awt.Color(59, 89, 152));
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnnuevoActionPerformed(evt);
            }
        });
        btnnuevo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnnuevoKeyPressed(evt);
            }
        });
        jPanel2.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 90, 50));

        btncancelar.setBackground(new java.awt.Color(59, 89, 152));
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, 90, 50));

        btnlimpia.setBackground(new java.awt.Color(59, 89, 152));
        btnlimpia.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpia.setText("Limpiar");
        btnlimpia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnlimpiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnlimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 100, 50));

        jcsucursal.setBackground(new java.awt.Color(223, 227, 238));
        jcsucursal.setForeground(new java.awt.Color(59, 89, 152));
        jcsucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcsucursal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcsucursalActionPerformed(evt);
            }
        });
        jPanel2.add(jcsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, -1));

        jctipoUsuario.setBackground(new java.awt.Color(223, 227, 238));
        jctipoUsuario.setForeground(new java.awt.Color(59, 89, 152));
        jctipoUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jctipoUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jctipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, -1));

        jcsexo.setBackground(new java.awt.Color(223, 227, 238));
        jcsexo.setForeground(new java.awt.Color(59, 89, 152));
        jcsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M" }));
        jcsexo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcsexoActionPerformed(evt);
            }
        });
        jcsexo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcsexoKeyPressed(evt);
            }
        });
        jPanel2.add(jcsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, -1));

        txtfecha.setBackground(new java.awt.Color(223, 227, 238));
        txtfecha.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 20));

        jPanel3.setBackground(new java.awt.Color(223, 227, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNameUser1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLNameUser1.setForeground(new java.awt.Color(59, 89, 152));
        jLNameUser1.setText("Gestión Empleados");
        jPanel3.add(jLNameUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 820));

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setForeground(new java.awt.Color(247, 247, 247));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(Acciones);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTable1.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 950, 480));

        btneditar.setBackground(new java.awt.Color(59, 89, 152));
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btneditarActionPerformed(evt);
            }
        });
        jPanel4.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 100, 50));

        btnelimiar.setBackground(new java.awt.Color(59, 89, 152));
        btnelimiar.setForeground(new java.awt.Color(255, 255, 255));
        btnelimiar.setText("Eliminar");
        btnelimiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnelimiarActionPerformed(evt);
            }
        });
        jPanel4.add(btnelimiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 100, 50));

        btnempleados.setBackground(new java.awt.Color(59, 89, 152));
        btnempleados.setForeground(new java.awt.Color(255, 255, 255));
        btnempleados.setText("Empleados");
        btnempleados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnempleadosActionPerformed(evt);
            }
        });
        jPanel4.add(btnempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 100, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 1020, 700));

        jPanel5.setBackground(new java.awt.Color(139, 157, 195));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLWelcome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLWelcome.setForeground(new java.awt.Color(223, 227, 238));
        jLWelcome.setText("Bienvenido:");
        jPanel5.add(jLWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLIconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gerente.png"))); // NOI18N
        jPanel5.add(jLIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLNameUser.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLNameUser.setForeground(new java.awt.Color(223, 227, 238));
        jPanel5.add(jLNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar2.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLCerrarMousePressed(evt);
            }
        });
        jPanel5.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 25, 40));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar2.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMousePressed(evt);
            }
        });
        jPanel5.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1020, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMousePressed
    {//GEN-HEADEREND:event_jLCerrarMousePressed
        this.dispose();
        new VtnMainAdmin().setVisible(true);
    }//GEN-LAST:event_jLCerrarMousePressed

    private void jLMinimizarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMousePressed
    {//GEN-HEADEREND:event_jLMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMousePressed

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseEntered
    {//GEN-HEADEREND:event_jLCerrarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/cerrar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseExited
    {//GEN-HEADEREND:event_jLCerrarMouseExited
        ImageIcon icon = new ImageIcon("src/images/cerrar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLMinimizarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseEntered
    {//GEN-HEADEREND:event_jLMinimizarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/minimizar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseEntered

    private void jLMinimizarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseExited
    {//GEN-HEADEREND:event_jLMinimizarMouseExited
        ImageIcon icon = new ImageIcon("src/images/minimizar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CrearModelo();
        llenaTabla();
        llenaTipos();

        llenaSucursales();

        cjb.ci.CtrlInterfaz.habilita(edicion, txtnombre, txtfecha, txtapellidoPaterno, txtapellidoMaterno, txtfecha, jcsucursal, jctipoUsuario, jcsexo, txtcurp, txttelefono, txtcorreo, txtcontraseña);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar);
        jLNameUser.setText(VtnLogin.emp.getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        edicion = false;
        cjb.ci.CtrlInterfaz.habilita(edicion, txtnombre, txtapellidoPaterno, txtapellidoMaterno, jcsucursal, jctipoUsuario, jcsexo, txtcurp, txttelefono, txtcorreo, txtcontraseña);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar);
        cjb.ci.CtrlInterfaz.limpia(txtnombre, txtapellidoPaterno, txtapellidoMaterno, txtcurp, txttelefono, txtcorreo, txtcontraseña);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnlimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiaActionPerformed
        cjb.ci.CtrlInterfaz.limpia(txtnombre, txtapellidoPaterno, txtapellidoMaterno, txtcurp, txttelefono, txtcorreo, txtcontraseña);
    }//GEN-LAST:event_btnlimpiaActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnnuevoActionPerformed
    {//GEN-HEADEREND:event_btnnuevoActionPerformed

        if (edicion)
        {
            if (Mensaje.pregunta(this, "¿Seguro que quiere dar de alta?") == JOptionPane.YES_OPTION)
            {
                Date date = txtfecha.getDate();
                long d = date.getTime();
                java.sql.Date fecha = new java.sql.Date(d);
                Calendar fech = new GregorianCalendar();
                String fech1 = String.valueOf(fech.get(Calendar.YEAR)) + "-" + String.valueOf(fech.get(Calendar.MONTH) + 1 + "-" + String.valueOf(fech.get(Calendar.DAY_OF_MONTH)));
                System.out.println(fecha);
                Empleados emp = new Empleados(0,
                        ExtraeId(String.valueOf(jcsucursal.getSelectedItem()), 0),
                        jctipoUsuario.getSelectedIndex() + 1,
                        txtnombre.getText(),
                        txtapellidoPaterno.getText(),
                        txtapellidoMaterno.getText(),
                        String.valueOf(jcsexo.getSelectedItem()).charAt(0),
                        String.valueOf(fecha),
                        txtcurp.getText(),
                        txttelefono.getText(),
                        txtcorreo.getText(),
                        txtcontraseña.getText(),
                        fech1);
                emp.inserta(this, emp, con);
                llenaTabla();
                edicion = false;
                btnnuevo.setText("Nuevo");
            }
        } else
        {
            edicion = true;
            jcsucursal.setEnabled(true);
            CtrlInterfaz.selecciona(txtnombre);
            CtrlInterfaz.habilita(edicion, txtnombre, txtapellidoPaterno, txtapellidoMaterno, txtcorreo, txtcontraseña, txtcurp, txttelefono, jctipoUsuario, jcsexo);

            CtrlInterfaz.limpia(txtnombre, txtapellidoPaterno, txtapellidoMaterno);
            btnnuevo.setText("Aceptar");
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnombreKeyPressed
    {//GEN-HEADEREND:event_txtnombreKeyPressed
        Validaciones.enter(this, evt, txtapellidoPaterno);
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtapellidoPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtapellidoPaternoKeyPressed
    {//GEN-HEADEREND:event_txtapellidoPaternoKeyPressed
        Validaciones.enter(this, evt, txtapellidoMaterno);
    }//GEN-LAST:event_txtapellidoPaternoKeyPressed

    private void txtcurpKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtcurpKeyPressed
    {//GEN-HEADEREND:event_txtcurpKeyPressed
        Validaciones.enter(this, evt, txttelefono);
    }//GEN-LAST:event_txtcurpKeyPressed

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txttelefonoKeyPressed
    {//GEN-HEADEREND:event_txttelefonoKeyPressed
        Validaciones.enter(this, evt, txtcorreo);
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void txtcorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtcorreoKeyPressed
    {//GEN-HEADEREND:event_txtcorreoKeyPressed
        Validaciones.enter(this, evt, txtcorreo);
    }//GEN-LAST:event_txtcorreoKeyPressed

    private void txtcontraseñaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtcontraseñaKeyPressed
    {//GEN-HEADEREND:event_txtcontraseñaKeyPressed
        Validaciones.enter(this, evt, btnnuevo);
    }//GEN-LAST:event_txtcontraseñaKeyPressed

    private void jcsucursalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcsucursalActionPerformed
    {//GEN-HEADEREND:event_jcsucursalActionPerformed

    }//GEN-LAST:event_jcsucursalActionPerformed

    private void jctipoUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jctipoUsuarioActionPerformed
    {//GEN-HEADEREND:event_jctipoUsuarioActionPerformed

    }//GEN-LAST:event_jctipoUsuarioActionPerformed

    private void txtapellidoMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtapellidoMaternoKeyPressed
    {//GEN-HEADEREND:event_txtapellidoMaternoKeyPressed
        Validaciones.enter(this, evt, jcsexo);
    }//GEN-LAST:event_txtapellidoMaternoKeyPressed

    private void jcsexoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcsexoKeyPressed
    {//GEN-HEADEREND:event_jcsexoKeyPressed
        Validaciones.enter(this, evt, txtfecha);
    }//GEN-LAST:event_jcsexoKeyPressed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnombreKeyTyped
    {//GEN-HEADEREND:event_txtnombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtapellidoPaternoKeyTyped
    {//GEN-HEADEREND:event_txtapellidoPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_txtapellidoPaternoKeyTyped

    private void txtapellidoMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtapellidoMaternoKeyTyped
    {//GEN-HEADEREND:event_txtapellidoMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_txtapellidoMaternoKeyTyped

    private void txtcurpKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtcurpKeyTyped
    {//GEN-HEADEREND:event_txtcurpKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_txtcurpKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txttelefonoKeyTyped
    {//GEN-HEADEREND:event_txttelefonoKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void btnnuevoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnnuevoKeyPressed
    {//GEN-HEADEREND:event_btnnuevoKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnnuevoActionPerformed(null);
        }
    }//GEN-LAST:event_btnnuevoKeyPressed

    private void jcsexoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcsexoActionPerformed
    {//GEN-HEADEREND:event_jcsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcsexoActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MousePressed
    {//GEN-HEADEREND:event_jTable1MousePressed
        if (!edicion)
        {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaTxt;
            jcsucursal.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1)));
            jctipoUsuario.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)));
            txtnombre.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3)));
            txtapellidoPaterno.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4)));
            txtapellidoMaterno.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5)));
            jcsexo.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6)));
            txtcurp.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 8)));
            txttelefono.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 9)));
            txtcorreo.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 10)));
            txtcontraseña.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 11)));

            try
            {
                fechaTxt = formatoFecha.parse(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 7)));
                txtfecha.setDate(fechaTxt);
            } catch (ParseException ex)
            {
                Logger.getLogger(VtnGestionEmpleadosGerente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EliminarActionPerformed
    {//GEN-HEADEREND:event_EliminarActionPerformed
        elimina();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificarActionPerformed
    {//GEN-HEADEREND:event_ModificarActionPerformed

    }//GEN-LAST:event_ModificarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        edita();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempleadosActionPerformed
        JasperReport reporte; //Creo el objeto reporte
        // Ubicacion del Reporte
        String path = "src\\Reportes\\empleados.jasper";
        try
        {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Cargo el reporte al objeto
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint, false); //Creamos la vista del Reporte
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex)
        {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnempleadosActionPerformed

    private void btnelimiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelimiarActionPerformed
        elimina();
    }//GEN-LAST:event_btnelimiarActionPerformed

    private void CrearModelo()
    {
        try
        {
            modelo = (new DefaultTableModel(
                    null, new String[]
                    {
                        "id_empleado", "id_sucursal", "id_tipousuario", "nombre", "Apellido_Paterno", "Apellido_Materno", "Sexo", "Fecha_Nacimiento", "Curp", "Telefono", "Correo", "Contraseña", "Fecha Alta"
                    })
            {
                Class[] types = new Class[]
                {
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                };
                boolean[] canEdit = new boolean[]
                {
                    false, false, false, false, false, false, false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex)
                {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex)
                {
                    return canEdit[colIndex];
                }
            });
            jTable1.setModel(modelo);
//            jTable1.getColumn("id_empleado").setPreferredWidth(0);
//            jTable1.getColumn("id_empleado").setMinWidth(0);
//            jTable1.getColumn("id_empleado").setWidth(0);
//            jTable1.getColumn("id_empleado").setMaxWidth(0);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    public void llenaTabla()
    {
//        Sucursal suc = new Sucursal();
//        modelo.addRow(suc.consultaMultipleMat(VtnLogin.con));
        modelo.setRowCount(0);
        try
        {
            PreparedStatement ps;
            ResultSet rs;
            String sql = "SELECT id_empleado,nombre_sucursal,tipo_usuario.tipo_usuario,nombre,apellido_paterno"
                    + ",apellido_materno,sexo,fecha_nacimiento ,curp, telefono_contacto,empleados.correo,"
                    + "password,fecha_alta FROM empleados WHERE id_sucursal=?" + VtnLogin.emp.getId_sucursal()
                    + "inner join sucursal on sucursal.id_sucursal = empleados.id_sucursal "
                    + "inner join tipo_usuario on tipo_usuario.id_tipousuario = empleados.id_tipousuario";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rrsw = rs.getMetaData();
            int cantcolumnas = rrsw.getColumnCount();
            Object[] filas = new Object[cantcolumnas];
            while (rs.next())
            {
                for (int i = 0; i < cantcolumnas; i++)
                {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (Exception e)
        {
            System.out.println("Error" + e.toString());
        }
    }

    public void llenaTipos()
    {

        Tipo_usuario tiusu = new Tipo_usuario();
        tipo = tiusu.consultaMultipleVec(con);
        if (tipo != null)
        {
            jctipoUsuario.removeAllItems();;
            for (int i = 0; i < tipo.length; i++)
            {
                jctipoUsuario.addItem(tipo[i].getTipo_usuario());
            }
        } else
        {
            Mensaje.error(this, "no carga estados");
        }
    }

    public void llenaSucursales()
    {

        Sucursal sucursal = new Sucursal();
        suc = sucursal.consultaMultipleVec(con);
        if (suc != null)
        {
            jcsucursal.removeAllItems();;
            for (int i = 0; i < suc.length; i++)
            {
                jcsucursal.addItem(suc[i].getNombre_sucursal());
            }
        } else
        {
            Mensaje.error(this, "no carga estados");
        }
    }

    public int ExtraeId(String nombre, int numero)
    {
        if (numero == 0)
        {
            for (int i = 0; i < suc.length; i++)
            {
                if (suc[i].getNombre_sucursal().equals(nombre))
                {
                    return suc[i].getId_sucursal();
                }
            }
        } else
        {
            for (int i = 0; i < tipo.length; i++)
            {
                if (tipo[i].getTipo_usuario().equals(nombre))
                {
                    return tipo[i].getId_tipousuario();
                }
            }
        }

        return 0;
    }

    public void elimina()
    {
        if (Mensaje.pregunta(this, "¿Desea Eliminar a usuario " + txtnombre.getText() + " " + txtapellidoPaterno.getText() + "?") == JOptionPane.YES_OPTION)
        {
            if (String.valueOf(jctipoUsuario.getSelectedItem()).equals("Administrador") || String.valueOf(jctipoUsuario.getSelectedItem()).equals("Gerente"))
            {
                Mensaje.error(this, "!! No se puede Eliminar a este usuario!!!");
            } else
            {
                Empleados emp = new Empleados();
                emp.elimina(this, Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))), con);
                llenaTabla();
                formWindowOpened(null);
            }
        }
    }

    public void edita()
    {
        try
        {
            if (edicion)
            {
                if (Mensaje.pregunta(this, "¿Seguro que quiere Editar?") == JOptionPane.YES_OPTION)
                {
                    Date date = txtfecha.getDate();
                    long d = date.getTime();
                    java.sql.Date fecha = new java.sql.Date(d);
                    Calendar fech = new GregorianCalendar();
                    String fech1 = String.valueOf(fech.get(Calendar.YEAR)) + "-" + String.valueOf(fech.get(Calendar.MONTH) + 1 + "-" + String.valueOf(fech.get(Calendar.DAY_OF_MONTH)));
                    System.out.println(fecha);
                    Empleados emp = new Empleados(
                            Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))),
                            ExtraeId(String.valueOf(jcsucursal.getSelectedItem()), 0),
                            jctipoUsuario.getSelectedIndex() + 1,
                            txtnombre.getText(),
                            txtapellidoPaterno.getText(),
                            txtapellidoMaterno.getText(),
                            String.valueOf(jcsexo.getSelectedItem()).charAt(0),
                            String.valueOf(fecha),
                            txtcurp.getText(),
                            txttelefono.getText(),
                            txtcorreo.getText(),
                            txtcontraseña.getText(),
                            fech1);
                    emp.modifica(this, emp, con);
                    llenaTabla();
                    edicion = false;
                    btneditar.setText("Editar");
                    btneditar.setText("Editar");
                    CtrlInterfaz.habilita(!edicion, btnnuevo, btnelimiar, btnempleados);

                    formWindowOpened(null);

                }
            } else
            {
                edicion = true;
                jcsucursal.setEnabled(true);
                CtrlInterfaz.selecciona(txtnombre);
                CtrlInterfaz.habilita(edicion, txtnombre, txtapellidoPaterno, txtapellidoMaterno, txtcorreo, txtcontraseña, txtcurp, txttelefono, txtfecha, jctipoUsuario, jcsexo);
                CtrlInterfaz.habilita(!edicion, btnnuevo, btnelimiar, btnempleados);
                btnnuevo.setText("Aceptar");
            }
        } catch (Exception e)
        {
            Mensaje.error(this, "Seleccione una celda");
            System.err.println(e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("GTK".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionEmpleadosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionEmpleadosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionEmpleadosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionEmpleadosGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnGestionEmpleadosGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Acciones;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnelimiar;
    private javax.swing.JButton btnempleados;
    private javax.swing.JButton btnlimpia;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLAMaterno;
    private javax.swing.JLabel jLAPaterno;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLContra;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLCurp;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLIDSucursal;
    private javax.swing.JLabel jLIDTipoUsuario;
    private javax.swing.JLabel jLIconAdmin;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLNameUser1;
    private javax.swing.JLabel jLNombreEmpleado;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLWelcome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcsexo;
    private javax.swing.JComboBox<String> jcsucursal;
    private javax.swing.JComboBox<String> jctipoUsuario;
    private javax.swing.JTextField txtapellidoMaterno;
    private javax.swing.JTextField txtapellidoPaterno;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcurp;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

}
