/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Objects.Estados;
import Objects.Sucursal;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static interfaces.VtnLogin.con;
import java.security.Principal;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author david
 */
public class VtnGestionSucursal extends javax.swing.JFrame
{

    static DefaultTableModel modelo;
    static Boolean edicion = false;
    static Estados[] est;

    /**
     * Creates new form VtnMainAdmin
     */
    public VtnGestionSucursal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Acciones = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jTFNombreSucursal = new javax.swing.JTextField();
        jLNombreSucursal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLTipoSucursal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLEstado = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jLDireccion = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTFTelefono = new javax.swing.JTextField();
        jLTipoSucursal1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTFCorreo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLCorreo = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jcestado = new javax.swing.JComboBox<>();
        jctipo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLNameUser1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        sucursales = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLWelcome = new javax.swing.JLabel();
        jLIconAdmin = new javax.swing.JLabel();
        jLNameUser = new javax.swing.JLabel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EliminarActionPerformed(evt);
            }
        });
        Acciones.add(Eliminar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ModificarActionPerformed(evt);
            }
        });
        Acciones.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal Administrador");
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(223, 227, 238));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFNombreSucursal.setBackground(new java.awt.Color(223, 227, 238));
        jTFNombreSucursal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTFNombreSucursal.setForeground(new java.awt.Color(59, 89, 152));
        jTFNombreSucursal.setBorder(null);
        jTFNombreSucursal.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNombreSucursalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNombreSucursalKeyTyped(evt);
            }
        });
        jPanel2.add(jTFNombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 20));

        jLNombreSucursal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLNombreSucursal.setForeground(new java.awt.Color(59, 89, 152));
        jLNombreSucursal.setText("Nombre de la sucursal:");
        jPanel2.add(jLNombreSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator2.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, 10));

        jSeparator3.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator3.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 10));

        jLTipoSucursal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLTipoSucursal.setForeground(new java.awt.Color(59, 89, 152));
        jLTipoSucursal.setText("Tipo de la sucursal:");
        jPanel2.add(jLTipoSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator4.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, 10));

        jLEstado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(59, 89, 152));
        jLEstado.setText("Estado:");
        jPanel2.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jTFDireccion.setBackground(new java.awt.Color(223, 227, 238));
        jTFDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTFDireccion.setForeground(new java.awt.Color(59, 89, 152));
        jTFDireccion.setBorder(null);
        jTFDireccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 20));

        jLDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLDireccion.setForeground(new java.awt.Color(59, 89, 152));
        jLDireccion.setText("Direccion:");
        jPanel2.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator5.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 10));

        jTFTelefono.setBackground(new java.awt.Color(223, 227, 238));
        jTFTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(59, 89, 152));
        jTFTelefono.setBorder(null);
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 150, 20));

        jLTipoSucursal1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLTipoSucursal1.setForeground(new java.awt.Color(59, 89, 152));
        jLTipoSucursal1.setText("Telefono:");
        jPanel2.add(jLTipoSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator6.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 150, 10));

        jTFCorreo.setBackground(new java.awt.Color(223, 227, 238));
        jTFCorreo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTFCorreo.setForeground(new java.awt.Color(59, 89, 152));
        jTFCorreo.setBorder(null);
        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 150, 20));

        jSeparator7.setBackground(new java.awt.Color(59, 89, 152));
        jSeparator7.setForeground(new java.awt.Color(59, 89, 152));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, 10));

        jLCorreo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLCorreo.setForeground(new java.awt.Color(59, 89, 152));
        jLCorreo.setText("Correo:");
        jPanel2.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        btnnuevo.setBackground(new java.awt.Color(59, 89, 152));
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 40));

        btncancelar.setBackground(new java.awt.Color(59, 89, 152));
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 100, 40));

        jButton1.setBackground(new java.awt.Color(59, 89, 152));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, 40));

        jcestado.setBackground(new java.awt.Color(223, 227, 238));
        jcestado.setForeground(new java.awt.Color(59, 89, 152));
        jcestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, -1));

        jctipo.setBackground(new java.awt.Color(223, 227, 238));
        jctipo.setForeground(new java.awt.Color(59, 89, 152));
        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria", "Secundaria" }));
        jctipo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jctipoActionPerformed(evt);
            }
        });
        jPanel2.add(jctipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, -1));

        jPanel3.setBackground(new java.awt.Color(223, 227, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNameUser1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLNameUser1.setForeground(new java.awt.Color(59, 89, 152));
        jLNameUser1.setText("Gestión sucursales");
        jPanel3.add(jLNameUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 810));

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setForeground(new java.awt.Color(247, 247, 247));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(Acciones);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(223, 227, 238));
        jTable1.setSelectionForeground(new java.awt.Color(139, 157, 195));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 930, 350));

        btneditar.setBackground(new java.awt.Color(59, 89, 152));
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btneditarActionPerformed(evt);
            }
        });
        jPanel4.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, 50));

        btneliminar.setBackground(new java.awt.Color(59, 89, 152));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 150, 50));

        sucursales.setBackground(new java.awt.Color(59, 89, 152));
        sucursales.setForeground(new java.awt.Color(255, 255, 255));
        sucursales.setText("Lista de sucursales");
        sucursales.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sucursalesActionPerformed(evt);
            }
        });
        jPanel4.add(sucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 150, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 1000, 700));

        jPanel5.setBackground(new java.awt.Color(139, 157, 195));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLWelcome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLWelcome.setForeground(new java.awt.Color(223, 227, 238));
        jLWelcome.setText("Bienvenido:");
        jPanel5.add(jLWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLIconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrador-con-ruedas-dentadas.png"))); // NOI18N
        jPanel5.add(jLIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLNameUser.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLNameUser.setForeground(new java.awt.Color(223, 227, 238));
        jPanel5.add(jLNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar2.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMousePressed(evt);
            }
        });
        jPanel5.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 30, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar2.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLCerrarMousePressed(evt);
            }
        });
        jPanel5.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 30, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 1000, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMousePressed
    {//GEN-HEADEREND:event_jLCerrarMousePressed
        this.dispose();
        new VtnMainAdmin().setVisible(true);
    }//GEN-LAST:event_jLCerrarMousePressed

    private void jLMinimizarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMousePressed
    {//GEN-HEADEREND:event_jLMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMousePressed

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseEntered
    {//GEN-HEADEREND:event_jLCerrarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/cerrar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseExited
    {//GEN-HEADEREND:event_jLCerrarMouseExited
        ImageIcon icon = new ImageIcon("src/images/cerrar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLMinimizarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseEntered
    {//GEN-HEADEREND:event_jLMinimizarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/minimizar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseEntered

    private void jLMinimizarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseExited
    {//GEN-HEADEREND:event_jLMinimizarMouseExited
        ImageIcon icon = new ImageIcon("src/images/minimizar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CrearModelo();
        llenaTabla();
        cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar, btneliminar, btneditar);
        llenaEstados();
        jLNameUser.setText(VtnLogin.emp.getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        if (edicion)
        {
            if (Mensaje.pregunta(this, "¿Seguro que quiere dar de alta?") == JOptionPane.YES_OPTION)
            {
                Sucursal suc = new Sucursal(0,
                        jTFNombreSucursal.getText(),
                        jctipo.getSelectedIndex() + 1,
                        ExtraeId(String.valueOf(jcestado.getSelectedItem())),
                        jTFDireccion.getText(),
                        jTFTelefono.getText(),
                        jTFCorreo.getText());
                suc.inserta(this, suc, con);
                llenaTabla();
                edicion = false;
                cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
                cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar, btneliminar, btneditar);
                btnnuevo.setText("Nuevo");
            }
        } else
        {
            edicion = true;
            CtrlInterfaz.selecciona(jTFNombreSucursal);
            cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
            cjb.ci.CtrlInterfaz.habilita(!edicion, btneditar, btneliminar);
            cjb.ci.CtrlInterfaz.limpia(jTFNombreSucursal, jTFTelefono, jTFDireccion, jTFCorreo);
            btnnuevo.setText("Aceptar");
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cjb.ci.CtrlInterfaz.limpia(jTFNombreSucursal, jTFTelefono, jTFDireccion, jTFCorreo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        edicion = false;
        cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
        cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar, btneliminar, btneditar);
        cjb.ci.CtrlInterfaz.limpia(jTFNombreSucursal, jTFTelefono, jTFDireccion, jTFCorreo);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (!edicion)
        {
            jTFNombreSucursal.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1)));
            jctipo.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)));
            jcestado.setSelectedItem(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3)));
            jTFDireccion.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4)));
            jTFTelefono.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5)));
            jTFCorreo.setText(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6)));
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        modifica();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        elimina();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jTFNombreSucursalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreSucursalKeyPressed
    {//GEN-HEADEREND:event_jTFNombreSucursalKeyPressed
        Validaciones.enter(this, evt, jctipo);
    }//GEN-LAST:event_jTFNombreSucursalKeyPressed

    private void jTFDireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFDireccionKeyPressed
    {//GEN-HEADEREND:event_jTFDireccionKeyPressed
        Validaciones.enter(this, evt, jTFTelefono);
    }//GEN-LAST:event_jTFDireccionKeyPressed

    private void jTFTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyPressed
    {//GEN-HEADEREND:event_jTFTelefonoKeyPressed
        Validaciones.enter(this, evt, jTFCorreo);
    }//GEN-LAST:event_jTFTelefonoKeyPressed

    private void jTFNombreSucursalKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreSucursalKeyTyped
    {//GEN-HEADEREND:event_jTFNombreSucursalKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFNombreSucursalKeyTyped

    private void jTFDireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFDireccionKeyTyped
    {//GEN-HEADEREND:event_jTFDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDireccionKeyTyped

    private void jTFTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyTyped
    {//GEN-HEADEREND:event_jTFTelefonoKeyTyped
        if (jTFTelefono.getText().length() >= 10)
        {
            evt.consume();
        }
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFTelefonoKeyTyped

    private void jTFCorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCorreoKeyTyped
    {//GEN-HEADEREND:event_jTFCorreoKeyTyped

    }//GEN-LAST:event_jTFCorreoKeyTyped

    private void jTFCorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCorreoKeyPressed
    {//GEN-HEADEREND:event_jTFCorreoKeyPressed
        Validaciones.enter(this, evt, btnnuevo);
    }//GEN-LAST:event_jTFCorreoKeyPressed

    private void jctipoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jctipoActionPerformed
    {//GEN-HEADEREND:event_jctipoActionPerformed

    }//GEN-LAST:event_jctipoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EliminarActionPerformed
    {//GEN-HEADEREND:event_EliminarActionPerformed
        elimina();
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ModificarActionPerformed
    {//GEN-HEADEREND:event_ModificarActionPerformed
        modifica();
    }//GEN-LAST:event_ModificarActionPerformed

    private void sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucursalesActionPerformed
        JasperReport reporte; //Creo el objeto reporte
        // Ubicacion del Reporte
        String path = "src\\Reportes\\sucursales.jasper";
        try
        {
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Cargo el reporte al objeto
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint, false); //Creamos la vista del Reporte
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex)
        {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sucursalesActionPerformed

    public void llenaTabla()
    {
//        Sucursal suc = new Sucursal();
//        modelo.addRow(suc.consultaMultipleMat(VtnLogin.con));
        modelo.setRowCount(0);
        try
        {
            PreparedStatement ps;
            ResultSet rs;
            String sql = "SELECT id_sucursal,nombre_sucursal,tipo_sucursal.tipo,nombre_estado,direccion,telefono,correo FROM sucursal "
                    + "inner join tipo_sucursal on tipo_sucursal.id_tiposucursal = sucursal.tipo "
                    + "inner join estados on estados.id_estado = sucursal.estado";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rrsw = rs.getMetaData();
            int cantcolumnas = rrsw.getColumnCount();
            Object[] filas = new Object[cantcolumnas];
            while (rs.next())
            {
                for (int i = 0; i < cantcolumnas; i++)
                {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (Exception e)
        {
            System.out.println("Error" + e.toString());
        }
    }

    private void CrearModelo()
    {
        try
        {
            modelo = (new DefaultTableModel(
                    null, new String[]
                    {
                        "id_sucursal", "nombre_sucursal", "tipo", "estado", "direccion", "telefono", "correo"
                    })
            {
                Class[] types = new Class[]
                {
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                };
                boolean[] canEdit = new boolean[]
                {
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex)
                {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex)
                {
                    return canEdit[colIndex];
                }
            });
            jTable1.setModel(modelo);
//            jTable1.getColumn("id_sucursal").setPreferredWidth(0);
//            jTable1.getColumn("id_sucursal").setMinWidth(0);
//            jTable1.getColumn("id_sucursal").setWidth(0);
//            jTable1.getColumn("id_sucursal").setMaxWidth(0);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    public void llenaEstados()
    {

        Estados est1 = new Estados();
        est = est1.consultaMultipleVec(con);
        if (est != null)
        {
            jcestado.removeAllItems();;
            for (int i = 0; i < est.length; i++)
            {
                jcestado.addItem(est[i].getNombre_estado());
            }
        } else
        {
            Mensaje.error(this, "no carga estados");
        }
    }

    public int ExtraeId(String nombre)
    {
        for (int i = 0; i < est.length; i++)
        {
            if (est[i].getNombre_estado().equals(nombre))
            {
                return est[i].getId_estado();
            }
        }
        return 0;
    }

    public void elimina()
    {
        try
        {
            if (Mensaje.pregunta(this, "¿Seguro que quiere eliminar a " + jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1) + "?") == JOptionPane.YES_OPTION)
            {
                if (String.valueOf(jctipo.getSelectedItem()).equals("Primaria"))
                {
                    Mensaje.error(this, "!!No se puede eliminar esta sucursal!!");
                } else
                {
                    Sucursal suc = new Sucursal();
                    suc.elimina(this, Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))), con);
                    llenaTabla();
                }
            }

        } catch (Exception e)
        {
            Mensaje.error(this, "Selecione un elemento de la tabla");
            System.out.println(e.toString());
        }
    }

    public void modifica()
    {
        try
        {
            if (edicion)
            {
                if (Mensaje.pregunta(this, "¿Seguro que quiere dar de editar a " + jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1) + "?") == JOptionPane.YES_OPTION)
                {
                    Sucursal suc = new Sucursal(Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))),
                            jTFNombreSucursal.getText(),
                            jctipo.getSelectedIndex() + 1,
                            ExtraeId(String.valueOf(jcestado.getSelectedItem())),
                            jTFDireccion.getText(),
                            jTFTelefono.getText(),
                            jTFCorreo.getText());
                    suc.modifica(this, suc, con);
                    llenaTabla();
                    edicion = false;
                    cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
                    cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btncancelar, btneliminar, btneditar);
                    btnnuevo.setText("Nuevo");
                }

            } else
            {
                if (null == jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0))
                {

                }
                edicion = true;
                cjb.ci.CtrlInterfaz.habilita(edicion, jTFNombreSucursal, jTFTelefono, jctipo, jcestado, jTFDireccion, jTFCorreo);
                cjb.ci.CtrlInterfaz.habilita(!edicion, btnnuevo, btneliminar);
                btnnuevo.setText("Aceptar");
            }
        } catch (Exception e)
        {
            Mensaje.error(this, "Selecione un elemento de la tabla");
            System.out.println(e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("GTK".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnGestionSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnGestionSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Acciones;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLIconAdmin;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLNameUser1;
    private javax.swing.JLabel jLNombreSucursal;
    private javax.swing.JLabel jLTipoSucursal;
    private javax.swing.JLabel jLTipoSucursal1;
    private javax.swing.JLabel jLWelcome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFNombreSucursal;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcestado;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JButton sucursales;
    // End of variables declaration//GEN-END:variables
    //CONECTA CON LA BASE DE DATOS

}
