/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Conextion.Conexiones;
import Objects.Empleados;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class VtnLogin extends javax.swing.JFrame {

    //Variables para VtnLogin
    int xy, xx;
    static Empleados emp;
    static Connection con = Conexiones.conectar();

    /**
     * Creates new form VtnLogin
     */
    public VtnLogin() {
        initComponents();
        jPOverlay.setBackground(new Color(223, 227, 238, 170));//Hace el panel transparente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPMain = new javax.swing.JPanel();
        jLCerrar = new javax.swing.JLabel();
        jLMinimizar = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jLUser = new javax.swing.JLabel();
        jSUser = new javax.swing.JSeparator();
        jLPass = new javax.swing.JLabel();
        jSPass = new javax.swing.JSeparator();
        jBLog = new javax.swing.JButton();
        jPFPass = new javax.swing.JPasswordField();
        jLLogo = new javax.swing.JLabel();
        jPOverlay = new javax.swing.JPanel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");
        setMinimumSize(new java.awt.Dimension(904, 504));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPMain.setBackground(new java.awt.Color(139, 157, 195));
        jPMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar1.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLCerrarMousePressed(evt);
            }
        });
        jPMain.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 14, 22, 24));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar1.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMousePressed(evt);
            }
        });
        jPMain.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 14, -1, -1));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(59, 89, 152));
        jLTitulo.setText("Inicio de sesión");
        jPMain.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 310, 36));

        jTFUser.setBackground(new java.awt.Color(139, 157, 195));
        jTFUser.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTFUser.setForeground(new java.awt.Color(59, 89, 152));
        jTFUser.setBorder(null);
        jTFUser.setCaretColor(new java.awt.Color(139, 157, 195));
        jTFUser.setDisabledTextColor(new java.awt.Color(139, 157, 195));
        jTFUser.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFUserKeyPressed(evt);
            }
        });
        jPMain.add(jTFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 310, 20));

        jLUser.setBackground(new java.awt.Color(255, 255, 255));
        jLUser.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLUser.setForeground(new java.awt.Color(59, 89, 152));
        jLUser.setText("Usuario:");
        jPMain.add(jLUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 310, -1));

        jSUser.setBackground(new java.awt.Color(59, 89, 152));
        jSUser.setForeground(new java.awt.Color(59, 89, 152));
        jPMain.add(jSUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 310, 10));

        jLPass.setBackground(new java.awt.Color(255, 255, 255));
        jLPass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLPass.setForeground(new java.awt.Color(59, 89, 152));
        jLPass.setText("Contraseña:");
        jPMain.add(jLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 310, -1));

        jSPass.setBackground(new java.awt.Color(59, 89, 152));
        jSPass.setForeground(new java.awt.Color(59, 89, 152));
        jPMain.add(jSPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 310, 10));

        jBLog.setBackground(new java.awt.Color(59, 89, 152));
        jBLog.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jBLog.setForeground(new java.awt.Color(255, 255, 255));
        jBLog.setText("Iniciar sesión");
        jBLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 89, 152)));
        jBLog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBLogActionPerformed(evt);
            }
        });
        jBLog.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jBLogKeyPressed(evt);
            }
        });
        jPMain.add(jBLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 310, 30));

        jPFPass.setBackground(new java.awt.Color(139, 157, 195));
        jPFPass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPFPass.setForeground(new java.awt.Color(59, 89, 152));
        jPFPass.setToolTipText("");
        jPFPass.setBorder(null);
        jPFPass.setCaretColor(new java.awt.Color(139, 157, 195));
        jPFPass.setDisabledTextColor(new java.awt.Color(139, 157, 195));
        jPFPass.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jPFPassKeyPressed(evt);
            }
        });
        jPMain.add(jPFPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 310, 20));

        getContentPane().add(jPMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 470, 520));

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jPOverlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPOverlayMouseDragged(evt);
            }
        });
        jPOverlay.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPOverlayMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPOverlayLayout = new javax.swing.GroupLayout(jPOverlay);
        jPOverlay.setLayout(jPOverlayLayout);
        jPOverlayLayout.setHorizontalGroup(
            jPOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPOverlayLayout.setVerticalGroup(
            jPOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 460, 520));

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bottles-layout.jpg"))); // NOI18N
        getContentPane().add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 447, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPOverlayMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPOverlayMouseDragged
    {//GEN-HEADEREND:event_jPOverlayMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPOverlayMouseDragged

    private void jPOverlayMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPOverlayMousePressed
    {//GEN-HEADEREND:event_jPOverlayMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPOverlayMousePressed

    private void jLCerrarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMousePressed
    {//GEN-HEADEREND:event_jLCerrarMousePressed
        this.dispose();
    }//GEN-LAST:event_jLCerrarMousePressed

    private void jLMinimizarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMousePressed
    {//GEN-HEADEREND:event_jLMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMousePressed

    private void jBLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBLogActionPerformed
    {//GEN-HEADEREND:event_jBLogActionPerformed
        emp = new Empleados(jTFUser.getText(), jPFPass.getText());
        emp = (Empleados) emp.consultaUnicausurio(jTFUser.getText(), con);
        if (emp.getCorreo() == null) {
            cjb.ci.CtrlInterfaz.selecciona(jTFUser);
            Mensaje.error(this, "Usuario no encontrado");
        } else {
            if (emp.getPassword().equals(jPFPass.getText())) {
                switch (emp.getId_tipousuario()) {
                    case 1:
                        new VtnMainAdmin().setVisible(true);
                        break;
                    case 2:
                        new VtnMainGerente().setVisible(true);
                        break;
                    case 3:
                        new VtnMainEmpleado().setVisible(true);
                        break;
                }
                this.dispose();
            }else{
                cjb.ci.CtrlInterfaz.selecciona(jPFPass);
                Mensaje.error(this, "Contraseña equivocada");
            }
        }
        System.out.println(emp.getNombre() + "tipo" + emp.getId_tipousuario());

    }//GEN-LAST:event_jBLogActionPerformed

    private void jLMinimizarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseEntered
    {//GEN-HEADEREND:event_jLMinimizarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/minimizar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseEntered

    private void jLMinimizarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseExited
    {//GEN-HEADEREND:event_jLMinimizarMouseExited
        ImageIcon icon = new ImageIcon("src/images/minimizar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseExited

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseEntered
    {//GEN-HEADEREND:event_jLCerrarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/cerrar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseExited
    {//GEN-HEADEREND:event_jLCerrarMouseExited
        ImageIcon icon = new ImageIcon("src/images/cerrar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jTFUserKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFUserKeyPressed
    {//GEN-HEADEREND:event_jTFUserKeyPressed
        Validaciones.enter(this, evt, jPFPass);
    }//GEN-LAST:event_jTFUserKeyPressed

    private void jPFPassKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFPassKeyPressed
    {//GEN-HEADEREND:event_jPFPassKeyPressed
        Validaciones.enter(this, evt, jBLog);
    }//GEN-LAST:event_jPFPassKeyPressed

    private void jBLogKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBLogKeyPressed
    {//GEN-HEADEREND:event_jBLogKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            jBLogActionPerformed(null);
        }
    }//GEN-LAST:event_jBLogKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLog;
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUser;
    private javax.swing.JPasswordField jPFPass;
    private javax.swing.JPanel jPMain;
    private javax.swing.JPanel jPOverlay;
    private javax.swing.JSeparator jSPass;
    private javax.swing.JSeparator jSUser;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
