/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class VtnMainAdmin extends javax.swing.JFrame
{

    /**
     * Creates new form VtnMainAdmin
     */
    public VtnMainAdmin()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLGA = new javax.swing.JLabel();
        jLIconAlamcen = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLGC = new javax.swing.JLabel();
        jLIconcategoria = new javax.swing.JLabel();
        btn_6 = new javax.swing.JPanel();
        ind_6 = new javax.swing.JPanel();
        jLGCl = new javax.swing.JLabel();
        jLIconCliente = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLGE = new javax.swing.JLabel();
        jLIconEmpleado = new javax.swing.JLabel();
        btn_7 = new javax.swing.JPanel();
        ind_7 = new javax.swing.JPanel();
        jLGProvee = new javax.swing.JLabel();
        jLIconProveedor = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLGP = new javax.swing.JLabel();
        jLIconProducto = new javax.swing.JLabel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLGS = new javax.swing.JLabel();
        jLIconSucursal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLIconAdmin = new javax.swing.JLabel();
        jLNameUser = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jLMinimizar = new javax.swing.JLabel();
        jLWelcome1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLHelp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLNameUser1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal Administrador");
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 89, 152));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_3.setBackground(new java.awt.Color(223, 227, 238));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_3MousePressed(evt);
            }
        });
        btn_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_3.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_3.add(ind_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGA.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGA.setForeground(new java.awt.Color(59, 89, 152));
        jLGA.setText("Gestionar almacenes");
        btn_3.add(jLGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconAlamcen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/almacen1.png"))); // NOI18N
        btn_3.add(jLIconAlamcen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, -1));

        btn_4.setBackground(new java.awt.Color(223, 227, 238));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_4MousePressed(evt);
            }
        });
        btn_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_4.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_4.add(ind_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGC.setForeground(new java.awt.Color(59, 89, 152));
        jLGC.setText("Gestionar Categorias");
        btn_4.add(jLGC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoria1.png"))); // NOI18N
        btn_4.add(jLIconcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 290, -1));

        btn_6.setBackground(new java.awt.Color(223, 227, 238));
        btn_6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_6MousePressed(evt);
            }
        });
        btn_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_6.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_6Layout = new javax.swing.GroupLayout(ind_6);
        ind_6.setLayout(ind_6Layout);
        ind_6Layout.setHorizontalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_6Layout.setVerticalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_6.add(ind_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGCl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGCl.setForeground(new java.awt.Color(59, 89, 152));
        jLGCl.setText("Gestionar Clientes");
        btn_6.add(jLGCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
        btn_6.add(jLIconCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 290, -1));

        btn_2.setBackground(new java.awt.Color(223, 227, 238));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_2MousePressed(evt);
            }
        });
        btn_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_2.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_2.add(ind_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGE.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGE.setForeground(new java.awt.Color(59, 89, 152));
        jLGE.setText("Gestionar empleados");
        btn_2.add(jLGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empleados.png"))); // NOI18N
        btn_2.add(jLIconEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, -1));

        btn_7.setBackground(new java.awt.Color(223, 227, 238));
        btn_7.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_7MousePressed(evt);
            }
        });
        btn_7.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btn_7KeyPressed(evt);
            }
        });
        btn_7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_7.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_7Layout = new javax.swing.GroupLayout(ind_7);
        ind_7.setLayout(ind_7Layout);
        ind_7Layout.setHorizontalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_7Layout.setVerticalGroup(
            ind_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_7.add(ind_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGProvee.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGProvee.setForeground(new java.awt.Color(59, 89, 152));
        jLGProvee.setText("Gestionar Proveedores");
        btn_7.add(jLGProvee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedor.png"))); // NOI18N
        btn_7.add(jLIconProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 290, -1));

        btn_5.setBackground(new java.awt.Color(223, 227, 238));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_5MousePressed(evt);
            }
        });
        btn_5.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btn_5KeyPressed(evt);
            }
        });
        btn_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_5.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_5.add(ind_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGP.setForeground(new java.awt.Color(59, 89, 152));
        jLGP.setText("Gestionar Productos");
        btn_5.add(jLGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/producto.png"))); // NOI18N
        btn_5.add(jLIconProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 290, -1));

        btn_1.setBackground(new java.awt.Color(223, 227, 238));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btn_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btn_1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                btn_1MousePressed(evt);
            }
        });
        btn_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_1.setBackground(new java.awt.Color(139, 157, 195));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btn_1.add(ind_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLGS.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLGS.setForeground(new java.awt.Color(59, 89, 152));
        jLGS.setText("Gestionar sucursales");
        btn_1.add(jLGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 20));

        jLIconSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sucursal.png"))); // NOI18N
        btn_1.add(jLIconSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 780));

        jPanel2.setBackground(new java.awt.Color(223, 227, 238));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(139, 157, 195));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLIconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrador-con-ruedas-dentadas.png"))); // NOI18N
        jPanel5.add(jLIconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLNameUser.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLNameUser.setForeground(new java.awt.Color(223, 227, 238));
        jPanel5.add(jLNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion2.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLCerrarMousePressed(evt);
            }
        });
        jPanel5.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 25, -1));

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar2.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMousePressed(evt);
            }
        });
        jPanel5.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLWelcome1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLWelcome1.setForeground(new java.awt.Color(223, 227, 238));
        jLWelcome1.setText("Bienvenido:");
        jPanel5.add(jLWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 514, 180));

        jPanel6.setBackground(new java.awt.Color(139, 157, 195));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel6MousePressed(evt);
            }
        });

        jLHelp.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLHelp.setForeground(new java.awt.Color(223, 227, 238));
        jLHelp.setText("Ayuda");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLHelp)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLHelp)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 510, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 520, 810));

        jPanel3.setBackground(new java.awt.Color(223, 227, 238));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNameUser1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLNameUser1.setForeground(new java.awt.Color(59, 89, 152));
        jLNameUser1.setText("Administrador");
        jPanel3.add(jLNameUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 790, 110));

        jPanel4.setBackground(new java.awt.Color(247, 247, 247));
        jPanel4.setForeground(new java.awt.Color(247, 247, 247));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 807));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 630, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMousePressed
    {//GEN-HEADEREND:event_jLCerrarMousePressed
        this.dispose();
        new VtnLogin().setVisible(true);
    }//GEN-LAST:event_jLCerrarMousePressed

    private void jLMinimizarMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMousePressed
    {//GEN-HEADEREND:event_jLMinimizarMousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMousePressed

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseEntered
    {//GEN-HEADEREND:event_jLCerrarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/cerrar-sesion1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseExited
    {//GEN-HEADEREND:event_jLCerrarMouseExited
        ImageIcon icon = new ImageIcon("src/images/cerrar-sesion2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLCerrar.setIcon(a);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLMinimizarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseEntered
    {//GEN-HEADEREND:event_jLMinimizarMouseEntered
        ImageIcon icon = new ImageIcon("src/images/minimizar1.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseEntered

    private void jLMinimizarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseExited
    {//GEN-HEADEREND:event_jLMinimizarMouseExited
        ImageIcon icon = new ImageIcon("src/images/minimizar2.png");
        Icon a = new ImageIcon(icon.getImage());
        jLMinimizar.setIcon(a);
    }//GEN-LAST:event_jLMinimizarMouseExited

    private void btn_3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_3MousePressed
    {//GEN-HEADEREND:event_btn_3MousePressed
        this.dispose();
        new VtnGestionAlmacen().setVisible(true);
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_3MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_3MouseEntered
    {//GEN-HEADEREND:event_btn_3MouseEntered
        btn_3.setBackground(new Color(139, 157, 195));
        ind_3.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_3MouseEntered

    private void btn_3MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_3MouseExited
    {//GEN-HEADEREND:event_btn_3MouseExited
        btn_3.setBackground(new Color(223, 227, 238));
        ind_3.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_3MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLNameUser.setText(VtnLogin.emp.getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void btn_4MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_4MouseEntered
    {//GEN-HEADEREND:event_btn_4MouseEntered
        btn_4.setBackground(new Color(139, 157, 195));
        ind_4.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_4MouseEntered

    private void btn_4MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_4MouseExited
    {//GEN-HEADEREND:event_btn_4MouseExited
        btn_4.setBackground(new Color(223, 227, 238));
        ind_4.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_4MouseExited

    private void btn_4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_4MousePressed
    {//GEN-HEADEREND:event_btn_4MousePressed
        this.dispose();
        new VtnGestionCategorias().setVisible(true);
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_6MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_6MouseEntered
    {//GEN-HEADEREND:event_btn_6MouseEntered
        btn_6.setBackground(new Color(139, 157, 195));
        ind_6.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_6MouseEntered

    private void btn_6MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_6MouseExited
    {//GEN-HEADEREND:event_btn_6MouseExited
        btn_6.setBackground(new Color(223, 227, 238));
        ind_6.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_6MouseExited

    private void btn_6MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_6MousePressed
    {//GEN-HEADEREND:event_btn_6MousePressed
        this.dispose();
        new VtnGestionClientes().setVisible(true);
    }//GEN-LAST:event_btn_6MousePressed

    private void btn_2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_2MouseEntered
    {//GEN-HEADEREND:event_btn_2MouseEntered
        btn_2.setBackground(new Color(139, 157, 195));
        ind_2.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_2MouseEntered

    private void btn_2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_2MouseExited
    {//GEN-HEADEREND:event_btn_2MouseExited
        btn_2.setBackground(new Color(223, 227, 238));
        ind_2.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_2MouseExited

    private void btn_2MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_2MousePressed
    {//GEN-HEADEREND:event_btn_2MousePressed
        this.dispose();
        new VtnGestionEmpleados().setVisible(true);
    }//GEN-LAST:event_btn_2MousePressed

    private void btn_7MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_7MouseEntered
    {//GEN-HEADEREND:event_btn_7MouseEntered
        btn_7.setBackground(new Color(139, 157, 195));
        ind_7.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_7MouseEntered

    private void btn_7MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_7MouseExited
    {//GEN-HEADEREND:event_btn_7MouseExited
        btn_7.setBackground(new Color(223, 227, 238));
        ind_7.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_7MouseExited

    private void btn_7MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_7MousePressed
    {//GEN-HEADEREND:event_btn_7MousePressed
        this.dispose();
        new VtnGestionProveedores().setVisible(true);
    }//GEN-LAST:event_btn_7MousePressed

    private void btn_7KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btn_7KeyPressed
    {//GEN-HEADEREND:event_btn_7KeyPressed
        this.dispose();
        new VtnGestionProductos().setVisible(true);
    }//GEN-LAST:event_btn_7KeyPressed

    private void btn_5MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_5MouseEntered
    {//GEN-HEADEREND:event_btn_5MouseEntered
        btn_5.setBackground(new Color(139, 157, 195));
        ind_5.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_5MouseEntered

    private void btn_5MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_5MouseExited
    {//GEN-HEADEREND:event_btn_5MouseExited
        btn_5.setBackground(new Color(223, 227, 238));
        ind_5.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_5MouseExited

    private void btn_5MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_5MousePressed
    {//GEN-HEADEREND:event_btn_5MousePressed
        this.dispose();
        new VtnGestionProductos().setVisible(true);
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_5KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btn_5KeyPressed
    {//GEN-HEADEREND:event_btn_5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5KeyPressed

    private void btn_1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_1MouseEntered
    {//GEN-HEADEREND:event_btn_1MouseEntered
        btn_1.setBackground(new Color(139, 157, 195));
        ind_1.setBackground(new Color(223, 227, 238));
    }//GEN-LAST:event_btn_1MouseEntered

    private void btn_1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_1MouseExited
    {//GEN-HEADEREND:event_btn_1MouseExited
        btn_1.setBackground(new Color(223, 227, 238));
        ind_1.setBackground(new Color(139, 157, 195));
    }//GEN-LAST:event_btn_1MouseExited

    private void btn_1MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_1MousePressed
    {//GEN-HEADEREND:event_btn_1MousePressed
        this.dispose();
        new VtnGestionSucursal().setVisible(true);
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btn_1MouseClicked
    {//GEN-HEADEREND:event_btn_1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel6MousePressed
    {//GEN-HEADEREND:event_jPanel6MousePressed
        
    }//GEN-LAST:event_jPanel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("GTK".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnMainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel btn_5;
    private javax.swing.JPanel btn_6;
    private javax.swing.JPanel btn_7;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_6;
    private javax.swing.JPanel ind_7;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLGA;
    private javax.swing.JLabel jLGC;
    private javax.swing.JLabel jLGCl;
    private javax.swing.JLabel jLGE;
    private javax.swing.JLabel jLGP;
    private javax.swing.JLabel jLGProvee;
    private javax.swing.JLabel jLGS;
    private javax.swing.JLabel jLHelp;
    private javax.swing.JLabel jLIconAdmin;
    private javax.swing.JLabel jLIconAlamcen;
    private javax.swing.JLabel jLIconCliente;
    private javax.swing.JLabel jLIconEmpleado;
    private javax.swing.JLabel jLIconProducto;
    private javax.swing.JLabel jLIconProveedor;
    private javax.swing.JLabel jLIconSucursal;
    private javax.swing.JLabel jLIconcategoria;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNameUser;
    private javax.swing.JLabel jLNameUser1;
    private javax.swing.JLabel jLWelcome1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
